### ISSUE TITLE
Failure and Error thrown when > 50 issues found

### ISSUE THREAD

**Issue by psyked** [Krizzu/eslint-check-action#1]
Trying this action out on an existing codebase and encountering an Error with a failure of: 
```
No more than 50 items are allowed; 169 were supplied.
```

It would seem that this is a result of the limit on Annotations to be added in a single API request, as per https://developer.github.com/v3/checks/runs/

> **The Checks API limits the number of annotations to a maximum of 50 per API request.** To create more than 50 annotations, you have to make multiple requests to the Update a check run endpoint. Each time you update the check run, annotations are appended to the list of annotations that already exist for the check run. For details about how you can view annotations on GitHub, see "About status checks".

**Comment by Krizzu** [comment]
Sorry it did so long for me to reply!

Thanks for raising that up, I'm going to look into it.
