### ISSUE TITLE
Keep getting ##[error]You must authenticate via a GitHub App.

### ISSUE THREAD

**Issue by reptile18** [Krizzu/eslint-check-action#9]
Have the default template you have on the README in my CI Github Action and seeing this error.

**Comment by krizzu** [comment]
hmm, never seen that before

Probably is related to [Github token used in workflows](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token)

**Comment by reptile18** [comment]
Yup, accidentally used a personal access token instead of the built-in GITHUB_TOKEN
